## It’s time to Welcome A.I. and Machine Learning into our Agile/Scrum teams and Ways of Working

### DEMO - 1: Story Point Calculation for Upcoming Sprint

<br/><br/><br/>
___A DEMO of calculating Story Points with Machine Learning___

<br/><br/><br/><br/>

In [73]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

<br/><br/>

### Let's read the DATA from the CSV file

<br/><br/>

In [74]:
df = pd.read_csv("team_sp_details.csv")

In [75]:
df

Strength  Leave Component    LOrR  Story_Points
0        5.0    0.5         A   Local          55.0
1        6.0    1.0         A  Remote          45.0
2        4.0    0.5         B   Local          75.0
3        7.0    2.5         C   Local          35.0
4        9.0    0.5         B  Remote          50.0
5        6.0    2.0         A  Remote          40.0
6        7.0    1.0         B  Remote          45.0
7        5.0    1.5         B   Local          50.0
8        7.0    3.0         C  Remote          30.0
9        6.0    2.5         C   Local          50.0
10       5.0    0.5         C   Local          60.0
11       7.0    1.0         C  Remote          55.0
12       6.0    1.0         A  Remote          45.0
13       7.0    1.5         C  Remote          40.0
14       6.0    2.0         B   Local          55.0
15       8.0    1.5         C   Local          60.0
16       6.0    0.5         D   Local          70.0
17       7.0    0.0         A   Local          70.0
18       5.0    0.5         B  Remote          60.0
19       NaN    NaN       NaN     NaN           NaN
20       NaN    NaN       NaN     NaN           NaN

<br/><br/><br/>

### Prepare the Data to be fed into Machine Learning Algorithm
<br/><br/><br/>

In [76]:
features= np.zeros((19,4))

In [77]:
column_num = 0
rows = 0
for values in df.iloc[0:19,0:1].values:
    features[rows][column_num] = values
    rows += 1

column_num = 1
rows = 0
for values in df.iloc[0:19,1:2].values:
    features[rows][column_num] = values
    rows += 1

column_num = 2
rows = 0
for values in df.iloc[0:19,2:3].values:
    if values == 'A':
        values = 0
    elif values == 'B':
        values = 1
    elif values == 'C':
        values = 2
    else:
        values = -1
    features[rows][column_num] = values
    rows += 1


column_num = 3
rows = 0
for values in df.iloc[0:19,3:4].values:
    if values == 'Local':
        values = 0
    elif values == 'Remote':
        values = 1
    else:
        values = -1
    features[rows][column_num] = values
    rows += 1



    
#features

In [78]:
#features = df.iloc[0:19,0:2].values
labels = df.iloc[0:19,4].values
type(labels)

numpy.ndarray

In [79]:
features, labels

(array([[ 5. ,  0.5,  0. ,  0. ],
        [ 6. ,  1. ,  0. ,  1. ],
        [ 4. ,  0.5,  1. ,  0. ],
        [ 7. ,  2.5,  2. ,  0. ],
        [ 9. ,  0.5,  1. ,  1. ],
        [ 6. ,  2. ,  0. ,  1. ],
        [ 7. ,  1. ,  1. ,  1. ],
        [ 5. ,  1.5,  1. ,  0. ],
        [ 7. ,  3. ,  2. ,  1. ],
        [ 6. ,  2.5,  2. ,  0. ],
        [ 5. ,  0.5,  2. ,  0. ],
        [ 7. ,  1. ,  2. ,  1. ],
        [ 6. ,  1. ,  0. ,  1. ],
        [ 7. ,  1.5,  2. ,  1. ],
        [ 6. ,  2. ,  1. ,  0. ],
        [ 8. ,  1.5,  2. ,  0. ],
        [ 6. ,  0.5, -1. ,  0. ],
        [ 7. ,  0. ,  0. ,  0. ],
        [ 5. ,  0.5,  1. ,  1. ]]),
 array([55., 45., 75., 35., 50., 40., 45., 50., 30., 50., 60., 55., 45.,
        40., 55., 60., 70., 70., 60.]))

In [80]:
labels.dtype, features.dtype

(dtype('float64'), dtype('float64'))

<br/><br/><br/><br/>

### Apply the data in Machine Learning Algorithm


<br/><br/>

___In here we'll be using K Nearest Neighbour M.L. Algorithm___

<br/><br/>

<br/><br/>

___Train the M.L. Algorithm with the available DATA___
<br/><br/>

In [81]:
knn = KNeighborsClassifier(n_neighbors=1)

In [82]:
knn.fit(features, labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

<br/><br/><br/><br/>

___Now the training is done and My Machine Learning Model is READY TO MAKE PREDICTIONS___

<br/><br/><br/><br/>

___INPUT___

- Team Strength
- Leaves
- Component
- Local Or Remote

<br/><br/><br/><br/>

In [89]:
Team_strength = 7
Leaves = 2.0
Component = 1
LocalOrRemote = 0

query = np.array([Team_strength, Leaves, Component, LocalOrRemote])

<br/><br/>

___Let's see what our M.L. Algorithm Predicts for the given Data___
<br/><br/>

In [90]:
knn.predict([query])

array([55.])

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/>

### Algorithm Selection 

___Machine Learning is all about Data Engineering and Algorithm Selection___

<br/><br/><br/><br/>

___For the above data, we can use another form of Supervised Learning Model called "Regression"___

<br/><br/>

___Difference => It will provide contineous values rather than the values provided with the Training Data___

<br/><br/><br/><br/>

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(features, labels)

<br/><br/><br/><br/>

___Let's query the same data using the new M.L. model which was trainind with same Data Set___

<br/><br/><br/><br/>

In [ ]:
Team_strength = 7
Leaves = 1.5
Component = 2
LocalOrRemote = 1

query = np.array([Team_strength, Leaves, Component, LocalOrRemote])

In [ ]:
lr.predict([query])